name: Deploy Azure Resources

on:
  push:
    branches:
      - main

env:
  AZURE_RESOURCE_GROUP: "rrblobtest"
  AZURE_LOCATION: "UK West"
  STORAGE_ACCOUNT_NAME: "test123434"
  LOG_ANALYTICS_WORKSPACE_NAME: "rrlogtest"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy Bicep template
      run: |
        az deployment group create \
          --resource-group $AZURE_RESOURCE_GROUP \
          --template-file bicep/main.bicep \
          --parameters location="$AZURE_LOCATION" \
                      storageAccountName="$STORAGE_ACCOUNT_NAME" \
                      logAnalyticsWorkspaceName="$LOG_ANALYTICS_WORKSPACE_NAME"
