name: Deploy Azure Resources

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Create Resource Group
      run: |
        az group create --name rrblobtest --location "UK South"

    - name: Deploy Storage Account
      run: |
        az deployment group create \
          --resource-group rrblobtest \
          --template-file bicep/storage-account.bicep \
          --parameters location="UK South" \
                      storageAccountName="test123434" \
                      containerName="images" \
                      allowedIP="92.16.42.251"

    - name: Fetch Log Analytics Workspace ID
      id: fetch_workspace_id
      run: |
        LOG_ANALYTICS_WORKSPACE_ID=$(az monitor log-analytics workspace show \
          --resource-group <log-analytics-resource-group> \
          --workspace-name rrlogtest \
          --query id -o tsv)
        echo "LOG_ANALYTICS_WORKSPACE_ID=${LOG_ANALYTICS_WORKSPACE_ID}" >> $GITHUB_ENV

    - name: Deploy Log Analytics Integration
      run: |
        az deployment group create \
          --resource-group rrblobtest \
          --template-file bicep/log-analytics-integration.bicep \
          --parameters storageAccountId="/subscriptions/<subscription-id>/resourceGroups/rrblobtest/providers/Microsoft.Storage/storageAccounts/test123434" \
                      logAnalyticsWorkspaceId="$LOG_ANALYTICS_WORKSPACE_ID"
