name: Deploy Azure Storage Account with Log Analytics Integration

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Ensure Resource Group Exists
      run: |
        if ! az group show --name rrblobtest &>/dev/null; then
          az group create --name rrblobtest --location "UK West"
        else
          echo "Resource group rrblobtest already exists."
        fi

    - name: Deploy Storage Account and Log Analytics Association
      run: |
        az deployment group create \
          --resource-group rrblobtest \
          --template-file bicep/main.bicep \
          --parameters location="UK West" \
                      storageAccountName="test123434" \
                      containerName="images" \
                      allowedIP="92.16.42.251" \
                      logAnalyticsWorkspaceName="rrlogtest"
