name: Deploy Storage Account with Diagnostic Settings

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Create Resource Group
      run: |
        az group create --name rrblobtest --location "UK South"

    - name: Create Storage Account
      run: |
        az storage account create \
          --name teststorage20241229 \
          --resource-group rrblobtest \
          --location "UK South" \
          --sku Standard_LRS \
          --kind StorageV2

    - name: Create Log Analytics Workspace
      run: |
        az monitor log-analytics workspace create \
          --resource-group rrblobtest \
          --workspace-name rrlogtest \
          --location "UK South"

    - name: Get Resource IDs
      id: get_ids
      run: |
        STORAGE_ACCOUNT_ID=$(az storage account show --name teststorage20241229 --resource-group rrblobtest --query "id" -o tsv)
        LOG_ANALYTICS_ID=$(az monitor log-analytics workspace show --name rrlogtest --resource-group rrblobtest --query "id" -o tsv)
        echo "STORAGE_ACCOUNT_ID=${STORAGE_ACCOUNT_ID}" >> $GITHUB_ENV
        echo "LOG_ANALYTICS_ID=${LOG_ANALYTICS_ID}" >> $GITHUB_ENV

    - name: Associate Log Analytics Workspace
      run: |
        az monitor diagnostic-settings create \
          --name "storageAccountDiagnostics" \
          --resource ${{ env.STORAGE_ACCOUNT_ID }} \
          --logs '[{"category": "StorageRead", "enabled": true},{"category": "StorageWrite", "enabled": true},{"category": "StorageDelete", "enabled": true}]' \
          --metrics '[{"category": "AllMetrics", "enabled": true}]' \
          --workspace ${{ env.LOG_ANALYTICS_ID }}
